#pragma once

namespace jh
{
	enum class eSFXType
	{
		BGM,
		BOSS_BGM,
		PLAYER_SWING_ATTACK_1,
		PLAYER_SWING_ATTACK_2,
		PLAYER_SWING_ATTACK_3,
		PLAYER_PUSH_ATTACK,
		PLAYER_HITTED,
		PLAYER_DIE,
		SKILL_BEAM,
		SKILL_STRIKE,
		SKILL_PUSH,
		PLAYER_LEVEL_UP,
		MONSTER_SPAWN,
		MONSTER_HITTED,
		MONSTER_SWING,
		BOSS_MONSTER_FISTING,
		BOSS_MONSTER_SWING,
		BOSS_MONSTER_GAS,
		BOSS_MONSTER_BUFF,
		BOSS_MONSTER_POWER_GAS,
		BOSS_MONSTER_HITTED,
		BOSS_MONSTER_DIE,
		COUNT
	};
}