#pragma once

namespace jh
{
	enum class eSFXType
	{
		BGM,
		BOSS_BGM,
		PLAYER_SWING_ATTACK_1,
		PLAYER_SWING_ATTACK_2,
		PLAYER_SWING_ATTACK_3,
		PLAYER_PUSH_ATTACK,
		PLAYER_HITTED_1,
		PLAYER_HITTED_2,
		PLAYER_DASH,
		PLAYER_DIE,
		PLAYER_ROLLING,
		PLAYER_FOOTSTEP,

		SKILL_BEAM,
		SKILL_STRIKE,
		SKILL_PUSH,

		PLAYER_LEVEL_UP,

		MONSTER_SPAWN,
		MONSTER_HITTED,
		MONSTER_DIE,
		MONSTER_SWING_1,
		MONSTER_SWING_2,
		MONSTER_SWING_3,
		MONSTER_ERUPTION,
		UI_LEVEL_UP_MOVING,
		UI_LEVEL_UP_CHOICE,

		BOSS_MONSTER_MOVING,
		BOSS_MONSTER_FISTING,
		BOSS_MONSTER_SWING,
		BOSS_MONSTER_ERUPTION,
		BOSS_MONSTER_BUFF,
		BOSS_MONSTER_POWER_ERUPTION,
		BOSS_MONSTER_HITTED,
		BOSS_MONSTER_DIE,
		COUNT
	};
}